[package]
name = "aubri"
version = "0.2.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.10.1"
clap = { version = "4.4", features = ["derive", "env"] }
cpal = "0.15.2"
rand = "0.8.5"
blake3 = "1.5.0"
bytemuck = { version = "1.14", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }
rpassword = "7.5.3"

# OpenGL ("glow") is universally supported.
eframe = { version = "0.27.2", default-features = false, features = ["default_fonts", "glow"] }